CREATE TABLE IF NOT EXISTS TBL_BOOKS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    book_name VARCHAR(250) NOT NULL,
    book_author VARCHAR(250) NOT NULL,
    ISBN VARCHAR(250) DEFAULT NULL
    );
